config/routes.rb
Rails.application.routes.draw do

  resources :users

  resources :projects do
    resources :tasks do
      resources :comments
    end
    resources :memberships
  end


  root "pages#index"

  get 'about' => 'pages#about', as: :about
  get 'terms' => 'pages#terms', as: :terms
  get 'faq'   => 'pages#faq',   as: :faq
  get '/sign-up' => 'registrations#new', as: :signup
  post '/sign-up' => 'registrations#create'
  get '/sign-in' => 'authentication#new', as: :signin
  post '/sign-in' => 'authentication#create'
  get '/sign-out' => 'authentication#destroy', as: :signout
  get '/tracker_projects/:id(.:format)' => 'pivotal_stories#show', as: :tracker_project
end

app/models/task.rb
class Task < ActiveRecord::Base

  validates :description, presence: true
  validate :due_date_cannot_be_in_the_past, on: :create

  def due_date_cannot_be_in_the_past
    if due_date.present? && due_date < Date.today
      errors.add(:due_date, "can't be in the past")
    end
  end

  belongs_to :project
  has_many :comments, dependent: :destroy

  def member?(project)
    projects.include?(project)
  end

end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action do
    @project = Project.find(params[:project_id])
  end
  before_action :set_task, only: [:show, :edit, :update, :destroy]
  before_action :authorize_member
  before_action do
    if current_user.admin || @project.users.include?(current_user)
    else
      raise AccessDenied
    end
  end

  def index
    if params[:show_by] == "all"
      @tasks = @project.tasks.all
    else
      @tasks = @project.tasks.order(params[:sort_by]).where(complete: false)
    end
  end

  def show
    @task = @project.tasks.find(params[:id])
    @comment = @task.comments.new
    @comments = @task.comments.all
  end

  def new
    @task = @project.tasks.new
  end

  def edit
    @task = @project.tasks.find(params[:id])
  end

  def create
    @task = @project.tasks.new(params.require(:task).permit(:description, :complete, :due_date))
    if @task.save
      redirect_to project_tasks_path, notice: 'Task was successfully created.'
    else
      render :new
    end
  end

  def update
    @task = @project.tasks.find(params[:id])
    if @task.update(params.require(:task).permit(:description, :complete, :due_date))
      redirect_to project_tasks_path, notice: 'Task was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @task = @project.tasks.find(params[:id])
    @task.destroy
    redirect_to project_tasks_path, notice: 'Task was successfully destroyed.'
  end

  private

  def set_task
    @task = @project.tasks.find(params[:id])
  end
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/tasks/_form.html.erb
<div class="page-header">
  <h2><%= title %></h2>
</div>
<%= form_for [@project, @task], html: {class: "form-horizontal"} do |f| %>

<div class="form-group">
  <div class="col-md-offset-2 col-md-6">
    <%= render "shared/errors", instance: @task %>
  </div>
</div>


<div class="form-group row">
  <%= f.label :description, class: "col-sm-2 control-label" %>
  <div class="col-sm-4">
    <%= f.text_field :description, class: 'form-control' %>
  </div>
</div>

<div class="form-group row">
  <%= f.label :due_date, class: "col-sm-2 control-label" %>
  <div class="col-sm-2">
    <%= f.date_field :due_date, class: "form-control" %>
  </div>
</div>

<% if @task.id %>
<div class="form-group">
  <div class="col-sm-offset-2 col-sm-10">
    <div class="checkbox">
      <label>
        <%= f.check_box :complete %> Complete
      </label>
    </div>
  </div>
</div>
<% end %>

<div class="form-group">
  <div class="col-sm-offset-2 col-sm-10">
    <%= f.submit class: 'btn btn-primary' %>
  </div>
</div>

<% end %>

app/views/tasks/edit.html.erb
<%= render 'form', title: "Edit Task" %>

app/views/tasks/index.html.erb
<div class="page-header">
  <h1>Task for <%= @project.name %>
    <small>
      <div class="pull-right">
        <%= link_to_unless params[:show_by] == 'all', 'All', project_tasks_path(@project, show_by: "all" ) %> |
        <%= link_to_unless !params[:show_by], 'Incomplete', project_tasks_path(@project) %>
        <%= link_to 'Create Task', new_project_task_path(@project), class: "btn btn-info" %>
      </div>
    </small>
  </h1>
</div>

<ol class="breadcrumb">
  <li><%= link_to "Projects", projects_path %></li>
  <li><%= link_to @project.name, project_path(@project) %></li>
  <li class="active">Tasks</li>
</ol>



<table class="table">
  <thead>
    <tr>
      <th><%= link_to "Description", params.merge(:sort_by => "description") %></th>
      <th><%= link_to "Due", params.merge(:sort_by => "date") %></th>
      <th>Complete</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @tasks.each do |task| %>
    <tr>
      <td><%= link_to task.description, project_task_path(task.project, task) %>
        <span class="badge"><%= task.comments.count %></span>
      </td>
      <td><%= task.complete %></td>
      <td>
        <% if task.due_date %>
        <%= task.due_date.strftime("%m/%d/%Y") %>
        <% else nil %>
        <%end%>
      </td>
      <td>
        <div class="pull-right">
          <td>
            <%= link_to 'Edit', edit_project_task_path(task.project, task), :class => "btn btn-info" %>
          </td>
          <td>
            <%= link_to "",
            project_task_path(task.project, task),
            method: :delete,
            data: {confirm: 'Are you sure?'},
            class: "glyphicon glyphicon-remove" %>
          </td>
        </div>
      </td>
    </tr>
    <% end %>
  </tbody>
</table>

app/views/tasks/new.html.erb
<%= render 'form', title: "Create a New Task" %>

app/views/tasks/show.html.erb
<!-- header -->
<div class="page-header">
  <h2><%= @task.description %>
    <%= link_to 'Edit', edit_project_task_path(@project, @task), :class => "btn btn-info pull-right" %>
  </h2>
  <!-- breadcrumb -->
  <ol class="breadcrumb">
    <li><%= link_to "Projects", projects_path %></li>
    <li><%= link_to @project.name, project_path(@project) %></li>
    <li><%= link_to "Tasks", project_tasks_path %></li>
    <li class="active"><%= @task.description %></li>
  </ol>
</div>

<!-- meta-info -->
<div class="row">
  <div class="col-md-12">
    <p>
      <strong>Due:</strong>
      <% if @task.due_date %>
      <%= @task.due_date.strftime("%m/%d/%Y") %>
      <% else nil %>
      <%end%>
    </p>
    <p>
      <strong>Complete:</strong>
      <%= @task.complete %>
    </p>
  </div>
</div>

<!-- comment header -->
<div class="row">
  <div class="col-md-12">
    <h1>Comments</h1>
  </div>
</div>
<!-- comment -->
<% @task.comments.all.each do |comment| %>
<div class="row">
  <div class="col-md-3">
    <% if comment.user_id %>
    <%= link_to comment.user.full_name, user_path(comment.user) %>
    <% else %>
    (deleted user)
    <% end %>
    <p class="text-muted"><%= time_ago_in_words(comment.created_at) %></p>
  </div>
  <div class="col-md-9">
    <%= comment.comment %>
  </div>
</div>
<% end %>



<!-- comment form -->
<div class="form-group row">
  <div class="col-md-offset-3 col-md-9">
    <%= form_for [@project, @task, @comment] do |f| %>
    <%= f.text_area :comment, class: "form-control" %>
    <br>
    <%= f.submit class: "btn btn-primary" %>
  </div>
</div>

<% end %>