config/routes.rb
Rails.application.routes.draw do

  resources :users

  resources :projects do
    resources :tasks do
      resources :comments
    end
    resources :memberships
  end


  root "pages#index"

  get 'about' => 'pages#about', as: :about
  get 'terms' => 'pages#terms', as: :terms
  get 'faq'   => 'pages#faq',   as: :faq
  get '/sign-up' => 'registrations#new', as: :signup
  post '/sign-up' => 'registrations#create'
  get '/sign-in' => 'authentication#new', as: :signin
  post '/sign-in' => 'authentication#create'
  get '/sign-out' => 'authentication#destroy', as: :signout
  get '/tracker_projects/:id(.:format)' => 'pivotal_stories#show', as: :tracker_project
end

app/models/project.rb
class Project < ActiveRecord::Base

  validates :name, presence: true, uniqueness: true, case_sensitive: false

  has_many :tasks, dependent: :destroy

  has_many :memberships, dependent: :delete_all

  has_many :users, through: :memberships

  def owner?(project)
    admin? || memberships.where(project_id: project.id, role:"owner").present?
  end

  def member?(project)
    projects.include?(project)
  end

end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :set_project, only: [:show, :edit, :update, :destroy]
  before_action :authorize_member, only: [:show]
  before_action :authorize_owner, only: [:edit, :update, :destroy]

  def index
    @projects = Project.all
    tracker_api = TrackerApi.new
    @tracker_projects = tracker_api.projects(current_user.pivotal_tracker_token)
  end

  def show
    @project = Project.find(params[:id])
  end

  def new
    @project = Project.new
  end

  def edit
    @project = Project.find(params[:id])
  end

  def create
    @project = Project.new(params.require(:project).permit(:name))
    if @project.save
      Membership.create(
      project: @project,
      user: current_user,
      role: 'owner'
      )
      redirect_to project_tasks_path(@project), notice: 'Project was successfully created.'
    else
      render :new
    end
  end

  def update
    @project = Project.find(params[:id])
    project_params = params.require(:project).permit(:name)
    if @project.update(project_params)
      redirect_to project_path, notice: 'Project was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @project = Project.find(params[:id])
    @project.destroy
    redirect_to projects_path, notice: 'Project was successfully deleted'
  end

  private

  def set_project
    @project = Project.find(params[:id])
  end

end

app/views/projects/_form.html.erb
<div class="page-header">
  <h2><%= title %></h2>
</div>

<%= form_for @project, html: {class: "form-horizontal"} do |f| %>


<div class="form-group">
  <div class="col-md-offset-2 col-md-6">
    <%= render "shared/errors", instance: @project %>
  </div>
</div>

<div class="form-group row">
  <%= f.label :name, class: "col-sm-2 control-label" %>
  <div class="col-sm-4">
    <%= f.text_field :name, class: "form-control" %>
  </div>
</div>

<div class="form-group">
  <div class="col-sm-offset-2 col-sm-10">
    <%= f.submit class: 'btn btn-primary' %>
  </div>
</div>

<% end %>

app/views/projects/edit.html.erb
<%= render 'form', title: "Edit Projects" %>

app/views/projects/index.html.erb
<%= page_header "My Projects" do %>
  <%= link_to 'Create Project', new_project_path, :class => "btn btn-info" %>
<% end %>


  <table class="table">
    <thead>
      <tr>
        <th>Name</th>
        <th>Members</th>
        <th>Tasks</th>
        <th></th>
      </tr>
    </thead>

    <tbody>
      <% current_user.projects.each do |project| %>
          <tr>
            <td>
              <%= link_to project.name, project_path(project) %>
            </td>
            <td>
              <%= link_to project.memberships.count, project_memberships_path(project) %>
            </td>
            <td>
              <%= link_to project.tasks.count, project_tasks_path(project) %>
            </td>
            <td>
              <% if current_user.owner?(project) %>
              <%= link_to 'edit', edit_project_path(project), :class => 'pull-right' %>
              <% end %>
            </td>
          </tr>
      <% end %>
    </tbody>
  </table>

  <h1>Pivotal Tracker Projects</h1>

  <table class="table">
    <thead>
      <tr>
        <th>Name</th>
        <th>
        </th>
      </tr>
    </thead>

    <tbody>
      <% @tracker_projects.each do |project| %>
      <tr>
        <td>
          <%= link_to project.name, tracker_project_path(project.id) %>
        </td>
      </tr>
      <% end %>
    </tbody>
  </table>

app/views/projects/new.html.erb
<%= render 'form', title: "Create Project" %>

app/views/projects/show.html.erb
<!-- header -->
<div class="page-header">
  <div class="pull-right">
    <% if current_user.owner?(@project) %>
    <%= link_to "Edit", edit_project_path(@project), class: "btn btn-info" %>
    <% end %>
  </div>
  <h1><%= @project.name %></h1>
</div>
<!-- breadcrumb -->
<ol class="breadcrumb">
  <li><%= link_to "Projects", projects_path %></li>
  <li class="active"><%= @project.name %></li>
</ol>

<div class="row">
  <div class="col-md-6">
    <p>
      <%= link_to pluralize(@project.tasks.count, "Task"), project_tasks_path(@project) %>
    </p>
    <p>
      <%= link_to pluralize(@project.memberships.count, "Membership"), project_memberships_path(@project) %>
    </p>
  </div>
</div>

<div class="well">
  <p>
    <strong>Delete Project</strong>
  </p>
  <p>
    Deleting this project will also delete
    <%= pluralize(@project.memberships.count, "Membership") %>,
    <%= pluralize(@project.tasks.count, "Task") %>
    and associated comments.
  </p>
  <%= link_to "Delete",
  project_path(@project),
  method: :delete,
  data: {confirm: "Are you sure?"},
  class: "btn btn-danger" %>
</div>