config/routes.rb
Rails.application.routes.draw do

  resources :users

  resources :projects do
    resources :tasks do
      resources :comments
    end
    resources :memberships
  end


  root "pages#index"

  get 'about' => 'pages#about', as: :about
  get 'terms' => 'pages#terms', as: :terms
  get 'faq'   => 'pages#faq',   as: :faq
  get '/sign-up' => 'registrations#new', as: :signup
  post '/sign-up' => 'registrations#create'
  get '/sign-in' => 'authentication#new', as: :signin
  post '/sign-in' => 'authentication#create'
  get '/sign-out' => 'authentication#destroy', as: :signout
  get '/tracker_projects/:id(.:format)' => 'pivotal_stories#show', as: :tracker_project
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta name="description" content="">
  <meta name="author" content="">

  <title>gCamp</title>

  <%= csrf_meta_tags %>
  <%= javascript_include_tag 'application' %>
  <%= stylesheet_link_tag 'application' %>
</head>

<!-- <body style= "padding-top: 100px"> -->
<body>

  <!-- navigation bar -->
  <div class="navbar navbar-inverse navbar-fixed-top" role="navigation">
    <div class="container">
      <%= link_to "gCamp", projects_path, class: "navbar-brand", id: "brand-color" %>
      <ul class="nav navbar-nav">
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown">
            My Projects
            <span class="caret"></span>
          </a>
          <ul class="dropdown-menu" role="menu">
            <% current_user.projects.each do |project| %>
            <li><%= link_to project.name, project_path(project) %></li>
            <% end %>
            <li class="divider"></li>
            <li><%= link_to "New Project", new_project_path %></li>
          </ul>
        </li>
          <li><%= link_to "Users", users_path %></li>
      </ul>

      <ul class="nav navbar-nav navbar-right">
        <% if current_user %>
        <li><%= link_to current_user.full_name, user_path(current_user) %></li>
        <li><%= link_to "Sign Out", signout_path %></li>
        <% else %>
        <li><%= link_to "Sign Up", signup_path %></li>
        <li><%= link_to "Sign In", signin_path %></li>
        <% end %>
      </ul>
    </div>
  </div>

  <!-- page content -->
  <div class="container">
    <% if notice != nil %>
    <div class="alert alert-success text-center">
      <%= notice %>
    </div>
    <% end %>
    <%= yield %>
  </div>

  <footer>
    <div class="container">
      <hr>
      <div class="row">
        <div class="col-md-12 text-center">
          <%= link_to "about", about_path %>
          |
          <%= link_to "terms", terms_path %>
          |
          <%= link_to "faq", faq_path %>
        </div>
        <div class="col-md-12 pull-right">
        </div>
      </div>
    </div>
  </footer>
</body>
</html>

app/views/layouts/public.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta name="description" content="">
  <meta name="author" content="">

  <title>gCamp</title>

  <%= csrf_meta_tags %>
  <%= javascript_include_tag 'application' %>
  <%= stylesheet_link_tag 'public_landing_page' %>
</head>

<!-- <body style= "padding-top: 100px"> -->
<body id="myPage" data-spy="scroll" data-target=".navbar" data-offset="60">

  <!-- navigation bar -->
  <div class="navbar navbar-inverse navbar-fixed-top" role="navigation">
    <div class="container">
      <%= link_to "gCamp", root_path, class: "navbar-brand", id: "brand-color" %>
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "SIGN UP", signup_path %></li>
        <li><%= link_to "SIGN IN", signin_path %></li>
      </ul>
    </div>
  </div>

  <!-- page content -->
  <div class="container">
    <% if notice != nil %>
    <div class="alert alert-success text-center">
      <%= notice %>
    </div>
    <% end %>
    <%= yield %>
  </div>

  <footer>
    <div class="container">
      <hr>
      <div class="row">
        <div class="col-md-6">
          <%= link_to "about", about_path %>
          |
          <%= link_to "terms", terms_path %>
          |
          <%= link_to "faq", faq_path %>
        </div>
        <div class="col-md-6 pull-right">
          <div class="pull-right">
            <%= link_to "https://students.gschool.it/cohorts/3/students/95" do %>
            <%= image_tag("gschool-logo_icon.png") %>
            <% end %>
            |
            <%= link_to "http://www.linkedin.com/pub/wesley-whitney/a5/aa4/442/" do %>
            <%= image_tag("linked_in_icon.png") %>
            <% end %>
            |
            <%= link_to "https://github.com/weswhitney" do %>
            <%= image_tag("GitHub-Mark_icon.png") %>
            <% end %>
            |
            <%= link_to "https://twitter.com/wes_whitney" do %>
            <%= image_tag("Twitter_logo_blue_icon.png") %>
            <% end %>
          </div>
        </div>
      </div>
    </div>
  </footer>
</body>
</html>